const facultyDashboardData = {
  "academicOffer": {
    "program": "Ingenier\u00eda Industrial",
    "period": "Septiembre 2026 - Febrero 2027",
    "curriculum": "CQPINDU01 - Malla Actualizada 2020",
    "level": "Grado",
    "totalHours": 7200,
    "totalCourses": 65,
    "cycles": 10,
    "itineraries": [
      "I1 Gesti\u00f3n de manufactura",
      "I2 Gesti\u00f3n de servicios"
    ],
    "source": "ESTRUCTURA CURRICULAR PDF_20260624_120415.pdf, dOCENTES cii.xlsx y detalle docentes.xlsx",
    "description": "La oferta acad\u00e9mica de Ingenier\u00eda Industrial se organiza en 10 ciclos de formaci\u00f3n de grado, con 65 cursos y 7200 horas totales. La estructura curricular integra bases cient\u00edficas, ingenier\u00eda aplicada, gesti\u00f3n de operaciones, calidad, log\u00edstica, seguridad, pr\u00e1cticas preprofesionales e integraci\u00f3n curricular."
  },
  "faculty": [
    {
      "id": "alvarez-lloret-edgar-paul",
      "nro": 1,
      "name": "\u00c1LVAREZ LLORET \u00c9DGAR PA\u00daL",
      "title": "Ingeniero Mec\u00e1nico",
      "formation": "Maestr\u00eda",
      "type": "Docente",
      "modality": "Titular",
      "belonging": "Docente exclusivo Industrial",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/ing-alvarez-lloret-edgar-paul-ms.jpg",
      "subjects": [
        {
          "id": "c3-mecanica-de-materiales-31",
          "cycle": 3,
          "group": "N3",
          "code": "19096",
          "subject": "MEC\u00c1NICA DE MATERIALES",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c4-tecnologia-de-materiales-39",
          "cycle": 4,
          "group": "N4",
          "code": "",
          "subject": "TECNOLOG\u00cdA DE MATERIALES",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c8-ingenieria-del-mantenimiento-82",
          "cycle": 8,
          "group": "N8",
          "code": "",
          "subject": "INGENIER\u00cdA DEL MANTENIMIENTO",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "alvarez-palomeque-lourdes-ximena",
      "nro": 2,
      "name": "\u00c1LVAREZ PALOMEQUE LOURDES XIMENA",
      "title": "Ingeniero Qu\u00edmico",
      "formation": "Maestr\u00eda",
      "type": "Docente",
      "modality": "Titular",
      "belonging": "Docente exclusivo Industrial",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/ing-alvarez-palomeque-lourdes-ximena-ms.jpg",
      "subjects": [
        {
          "id": "c2-introduccion-a-la-ingenieria-industrial-24",
          "cycle": 2,
          "group": "N2",
          "code": "19033",
          "subject": "INTRODUCCI\u00d3N A LA INGENIER\u00cdA INDUSTRIAL",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 44,
          "role": "ACD"
        },
        {
          "id": "c5-ingenieria-de-procesos-y-ergonomia-53",
          "cycle": 5,
          "group": "N5",
          "code": "",
          "subject": "INGENIER\u00cdA DE PROCESOS Y ERGONOM\u00cdA",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c8-gestion-ambiental-empresarial-81",
          "cycle": 8,
          "group": "N8",
          "code": "",
          "subject": "GESTI\u00d3N AMBIENTAL EMPRESARIAL",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "andres-montero",
      "nro": 3,
      "name": "ANDRES MONTERO",
      "title": "Ingeniero Civil",
      "formation": "PhD",
      "type": "Docente",
      "modality": "Ocasional",
      "belonging": "Docente compartido",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/ing-montero-izquierdo-ivan-andres-phd.jpg",
      "subjects": [
        {
          "id": "c7-tecnologia-energetica-75",
          "cycle": 7,
          "group": "N7",
          "code": "",
          "subject": "TECNOLOG\u00cdA ENERG\u00c9TICA",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "barragan-landy-milton-francisco",
      "nro": 4,
      "name": "BARRAG\u00c1N LANDY MILTON FRANCISCO",
      "title": "Ingeniero Industrial",
      "formation": "PhD",
      "type": "Docente",
      "modality": "Titular",
      "belonging": "Docente compartido",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/ing-barragan-landy-milton-francisco-phd.jpg",
      "subjects": [
        {
          "id": "c9-lean-services-y-sigma-sigma-i-87",
          "cycle": 9,
          "group": "N9",
          "code": "",
          "subject": "LEAN SERVICES Y SIGMA SIGMA (I)",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 6,
          "role": "ACD"
        },
        {
          "id": "c10-innovation-management-99",
          "cycle": 10,
          "group": "N10",
          "code": "",
          "subject": "INNOVATION MANAGEMENT",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 24,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "espinoza-hernandez-paulina-rebeca",
      "nro": 5,
      "name": "ESPINOZA HERN\u00c1NDEZ PAULINA REBECA",
      "title": "Ingeniero Industrial",
      "formation": "Maestr\u00eda",
      "type": "Docente",
      "modality": "Titular",
      "belonging": "Docente compartido",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/ing-espinoza-hernandez-paulina-rebeca-ms.jpg",
      "subjects": [
        {
          "id": "c7-seguridad-y-salud-ocupacional-74",
          "cycle": 7,
          "group": "N7",
          "code": "",
          "subject": "SEGURIDAD Y SALUD OCUPACIONAL",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "fernando-cajamarca",
      "nro": 6,
      "name": "FERNANDO CAJAMARCA",
      "title": "Ingeniero Mec\u00e1nico",
      "formation": "Maestr\u00eda",
      "type": "T\u00e9cnico docente",
      "modality": "Ocasional",
      "belonging": "Docente exclusivo Industrial",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/default-profile.png",
      "subjects": []
    },
    {
      "id": "flores-siguenza-pablo-andres",
      "nro": 7,
      "name": "FLORES SIGUENZA PABLO ANDR\u00c9S",
      "title": "Ingeniero Industrial",
      "formation": "PhD",
      "type": "Docente",
      "modality": "Ocasional",
      "belonging": "Docente exclusivo Industrial",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/ing-flores-siguenza-pablo-andres-phd.jpg",
      "subjects": [
        {
          "id": "c1-metodologia-de-la-investigacion-g1-7",
          "cycle": 1,
          "group": "N1 G1 PARALELO A",
          "code": "19028",
          "subject": "METODOLOG\u00cdA DE LA INVESTIGACI\u00d3N G1",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c2-calculo-integral-26",
          "cycle": 2,
          "group": "N2",
          "code": "19031",
          "subject": "C\u00c1LCULO INTEGRAL",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 44,
          "role": "ACD"
        },
        {
          "id": "c8-sistemas-de-control-de-la-produccion-78",
          "cycle": 8,
          "group": "N8",
          "code": "",
          "subject": "SISTEMAS DE CONTROL DE LA PRODUCCI\u00d3N",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c9-instrumentacion-y-control-88",
          "cycle": 9,
          "group": "N9",
          "code": "",
          "subject": "INSTRUMENTACI\u00d3N Y CONTROL",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 26,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "freddy-bustamante",
      "nro": 8,
      "name": "FREDDY BUSTAMANTE",
      "title": "Bioqu\u00edmico Farmac\u00e9utico",
      "formation": "Maestr\u00eda",
      "type": "T\u00e9cnico docente",
      "modality": "Ocasional",
      "belonging": "Docente compartido",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/bqf-bustamante-pacheco-freddy-enrique.jpg",
      "subjects": [
        {
          "id": "c2-quimica-organica-22",
          "cycle": 2,
          "group": "N2",
          "code": "19856",
          "subject": "QU\u00cdMICA ORG\u00c1NICA",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 44,
          "role": "Pr\u00e1cticas"
        }
      ]
    },
    {
      "id": "guaman-guachichullca-noe-rodrigo",
      "nro": 9,
      "name": "GUAMAN GUACHICHULLCA NO\u00c9 RODRIGO",
      "title": "Ingeniero Industrial",
      "formation": "PhD candidate",
      "type": "Docente",
      "modality": "Ocasional",
      "belonging": "Docente exclusivo Industrial",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/ing-guaman-guachichullca-noe-rodrigo-mba.jpg",
      "subjects": [
        {
          "id": "c3-estadistica-analitica-33",
          "cycle": 3,
          "group": "N3",
          "code": "19094",
          "subject": "ESTAD\u00cdSTICA ANAL\u00cdTICA",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 44,
          "role": "ACD"
        },
        {
          "id": "c6-investigacion-y-desarrollo-de-nuevos-productos-p1-61",
          "cycle": 6,
          "group": "6",
          "code": "",
          "subject": "INVESTIGACI\u00d3N Y DESARROLLO DE NUEVOS PRODUCTOS P1",
          "acd": 3,
          "ape": 2,
          "aa": 4,
          "offer": 16,
          "role": "ACD"
        },
        {
          "id": "c6-investigacion-y-desarrollo-de-nuevos-productos-p2-62",
          "cycle": 6,
          "group": "6",
          "code": "",
          "subject": "INVESTIGACI\u00d3N Y DESARROLLO DE NUEVOS PRODUCTOS P2",
          "acd": 3,
          "ape": 2,
          "aa": 4,
          "offer": 16,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "guaman-ortiz-franklin-eduardo",
      "nro": 10,
      "name": "GUAM\u00c1N ORTIZ FRANKLIN EDUARDO",
      "title": "Ingeniero Electr\u00f3nico",
      "formation": "PhD candidate",
      "type": "Docente",
      "modality": "Ocasional",
      "belonging": "Docente exclusivo Industrial",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/ing-guaman-ortiz-franklin-eduardo-ms.jpg",
      "subjects": [
        {
          "id": "c1-calculo-diferencial-g2-14",
          "cycle": 1,
          "group": "N1 G2 PARALELO B",
          "code": "19026",
          "subject": "C\u00c1LCULO DIFERENCIAL G2",
          "acd": 3,
          "ape": 4,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c1-algebra-lineal-g1-10",
          "cycle": 1,
          "group": "N1 G1 PARALELO A",
          "code": "19025",
          "subject": "\u00c1LGEBRA LINEAL G1",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c1-algebra-lineal-g2-16",
          "cycle": 1,
          "group": "N1 G2 PARALELO B",
          "code": "19025",
          "subject": "\u00c1LGEBRA LINEAL G2",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c3-ingenieria-y-tecnologia-electricas-32",
          "cycle": 3,
          "group": "N3",
          "code": "19095",
          "subject": "INGENIER\u00cdA Y TECNOLOG\u00cdA EL\u00c9CTRICAS",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 40,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "guanuchi-quito-alexandra-elizabeth",
      "nro": 11,
      "name": "GUANUCHI QUITO ALEXANDRA ELIZABETH",
      "title": "Ingeniero Qu\u00edmico",
      "formation": "PhD candidate",
      "type": "Docente",
      "modality": "Titular",
      "belonging": "Docente compartido",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/default-profile.png",
      "subjects": [
        {
          "id": "c4-transporte-de-fluidos-40",
          "cycle": 4,
          "group": "N4",
          "code": "",
          "subject": "TRANSPORTE DE FLUIDOS",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "iniguez-moran-andrea-maria",
      "nro": 12,
      "name": "\u00cd\u00d1IGUEZ MOR\u00c1N ANDREA MAR\u00cdA",
      "title": "Ingeniero Qu\u00edmico",
      "formation": "Maestr\u00eda",
      "type": "Docente",
      "modality": "Ocasional",
      "belonging": "Docente exclusivo Industrial",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/ing-iniguez-moran-andrea-maria-mba.jpg",
      "subjects": [
        {
          "id": "c1-quimica-general-g1-6",
          "cycle": 1,
          "group": "N1 G1 PARALELO A",
          "code": "19029",
          "subject": "QU\u00cdMICA GENERAL G1",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c1-quimica-general-g2-17",
          "cycle": 1,
          "group": "N1 G2 PARALELO B",
          "code": "19029",
          "subject": "QU\u00cdMICA GENERAL G2",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c2-quimica-organica-22",
          "cycle": 2,
          "group": "N2",
          "code": "19856",
          "subject": "QU\u00cdMICA ORG\u00c1NICA",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 44,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "jadan-aviles-diana-carolina",
      "nro": 13,
      "name": "JAD\u00c1N AVIL\u00c9S DIANA CAROLINA",
      "title": "Ingeniero Industrial",
      "formation": "PhD candidate",
      "type": "Docente",
      "modality": "Titular",
      "belonging": "Docente compartido",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/default-profile.png",
      "subjects": [
        {
          "id": "c6-investigacion-operativa-63",
          "cycle": 6,
          "group": "6",
          "code": "",
          "subject": "INVESTIGACI\u00d3N OPERATIVA",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c9-unidad-de-integracion-curricular-1-93",
          "cycle": 9,
          "group": "N9",
          "code": "",
          "subject": "UNIDAD DE INTEGRACI\u00d3N CURRICULAR 1",
          "acd": 0,
          "ape": 1,
          "aa": 5,
          "offer": 26,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "james-arias",
      "nro": 14,
      "name": "JAMES ARIAS",
      "title": "Ingeniero Qu\u00edmico",
      "formation": "Maestr\u00eda",
      "type": "Docente",
      "modality": "Ocasional",
      "belonging": "Docente exclusivo Industrial",
      "dedication": "Tiempo parcial",
      "image": "assets/faculty/default-profile.png",
      "subjects": [
        {
          "id": "c10-simulacion-de-la-produccion-100",
          "cycle": 10,
          "group": "N10",
          "code": "",
          "subject": "SIMULACI\u00d3N DE LA PRODUCCI\u00d3N",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 24,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "jerves-mora-rodrigo-saul",
      "nro": 15,
      "name": "JERVES MORA RODRIGO SA\u00daL",
      "title": "Psic\u00f3logo",
      "formation": "Maestr\u00eda",
      "type": "Docente",
      "modality": "Titular",
      "belonging": "Docente exclusivo Industrial",
      "dedication": "Medio Tiempo",
      "image": "assets/faculty/psic-jerves-mora-rodrigo-saul-ms.jpg",
      "subjects": [
        {
          "id": "c5-psicologia-industrial-54",
          "cycle": 5,
          "group": "N5",
          "code": "",
          "subject": "PSICOLOG\u00cdA INDUSTRIAL",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c5-etica-de-la-ciencia-52",
          "cycle": 5,
          "group": "N5",
          "code": "",
          "subject": "\u00c9TICA DE LA CIENCIA",
          "acd": 1,
          "ape": 1,
          "aa": 1,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c6-gestion-del-talento-humano-60",
          "cycle": 6,
          "group": "6",
          "code": "",
          "subject": "GESTI\u00d3N DEL TALENTO HUMANO",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "llivisaca-villazhanay-juan-carlos",
      "nro": 16,
      "name": "LLIVISACA VILLAZHA\u00d1AY JUAN CARLOS",
      "title": "Ingeniero Industrial",
      "formation": "PhD candidate",
      "type": "Docente",
      "modality": "Titular",
      "belonging": "Docente exclusivo Industrial",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/ing-llivisaca-villazhanay-juan-carlos-ms.jpg",
      "subjects": [
        {
          "id": "c4-tecnicas-de-inferencia-estadistica-42",
          "cycle": 4,
          "group": "N4",
          "code": "",
          "subject": "T\u00c9CNICAS DE INFERENCIA ESTAD\u00cdSTICA",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c9-diseno-experimental-89",
          "cycle": 9,
          "group": "N9",
          "code": "",
          "subject": "DISE\u00d1O EXPERIMENTAL",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 26,
          "role": "ACD"
        },
        {
          "id": "c9-lean-manufacturing-y-6-sigma-i-86",
          "cycle": 9,
          "group": "N9",
          "code": "",
          "subject": "LEAN MANUFACTURING Y 6 SIGMA (I)",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 16,
          "role": "ACD"
        },
        {
          "id": "c10-lean-manufacturing-y-six-sigma-ii-i1-98",
          "cycle": 10,
          "group": "N10",
          "code": "",
          "subject": "LEAN MANUFACTURING Y SIX SIGMA (II) I1",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 24,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "mateo-coello",
      "nro": 17,
      "name": "MATEO COELLO",
      "title": "Economista",
      "formation": "Maestr\u00eda",
      "type": "Docente",
      "modality": "Ocasional",
      "belonging": "Docente exclusivo Industrial",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/default-profile.png",
      "subjects": [
        {
          "id": "c4-contabilidad-41",
          "cycle": 4,
          "group": "N4",
          "code": "",
          "subject": "CONTABILIDAD",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c5-costos-y-presupuestos-de-produccion-48",
          "cycle": 5,
          "group": "N5",
          "code": "",
          "subject": "COSTOS Y PRESUPUESTOS DE PRODUCCI\u00d3N",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c6-legislacion-ecuatoriana-64",
          "cycle": 6,
          "group": "6",
          "code": "",
          "subject": "LEGISLACI\u00d3N ECUATORIANA",
          "acd": 1,
          "ape": 1,
          "aa": 1,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c7-matematica-financiera-71",
          "cycle": 7,
          "group": "N7",
          "code": "",
          "subject": "MATEM\u00c1TICA FINANCIERA",
          "acd": 2,
          "ape": 1,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c9-sistemas-de-informacion-estrategica-90",
          "cycle": 9,
          "group": "N9",
          "code": "",
          "subject": "SISTEMAS DE INFORMACI\u00d3N ESTRAT\u00c9GICA",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 26,
          "role": "ACD"
        },
        {
          "id": "c10-diseno-y-gestion-de-proyectos-96",
          "cycle": 10,
          "group": "N10",
          "code": "",
          "subject": "DISE\u00d1O Y GESTI\u00d3N DE PROYECTOS",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 24,
          "role": "ACD"
        },
        {
          "id": "c10-gestion-estrategica-97",
          "cycle": 10,
          "group": "N10",
          "code": "",
          "subject": "GESTI\u00d3N ESTRAT\u00c9GICA",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 24,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "mejia-guaman-christian-fernando",
      "nro": 18,
      "name": "MEJ\u00cdA GUAM\u00c1N CHRISTIAN FERNANDO",
      "title": "F\u00edsico",
      "formation": "PhD",
      "type": "Docente",
      "modality": "Ocasional",
      "belonging": "Docente exclusivo Industrial",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/fis-mejia-guaman-christian-fernando-phd.jpg",
      "subjects": [
        {
          "id": "c1-fisica-i-g1-8",
          "cycle": 1,
          "group": "N1 G1 PARALELO A",
          "code": "19027",
          "subject": "F\u00cdSICA I G1",
          "acd": 4,
          "ape": 4,
          "aa": 4,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c2-fisica-ii-25",
          "cycle": 2,
          "group": "N2",
          "code": "19032",
          "subject": "F\u00cdSICA II",
          "acd": 3,
          "ape": 4,
          "aa": 2,
          "offer": 44,
          "role": "ACD"
        },
        {
          "id": "c3-termodinamica-30",
          "cycle": 3,
          "group": "N3",
          "code": "19097",
          "subject": "TERMODIN\u00c1MICA",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "narvaez-buestan-freddy-eduardo",
      "nro": 19,
      "name": "NARVAEZ BUEST\u00c1N FREDDY EDUARDO",
      "title": "Ingeniero Mec\u00e1nico",
      "formation": "PhD candidate",
      "type": "Docente",
      "modality": "Ocasional",
      "belonging": "Docente exclusivo Industrial",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/ing-narvaez-buestan-freddy-eduardo-msc.jpg",
      "subjects": [
        {
          "id": "c1-calculo-diferencial-g1-9",
          "cycle": 1,
          "group": "N1 G1 PARALELO A",
          "code": "19026",
          "subject": "C\u00c1LCULO DIFERENCIAL G1",
          "acd": 3,
          "ape": 4,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c4-metodos-numericos-43",
          "cycle": 4,
          "group": "N4",
          "code": "",
          "subject": "M\u00c9TODOS NUM\u00c9RICOS",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c4-transferencia-de-calor-38",
          "cycle": 4,
          "group": "N4",
          "code": "",
          "subject": "TRANSFERENCIA DE CALOR",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c6-maquinas-herramientas-y-accesorios-58",
          "cycle": 6,
          "group": "6",
          "code": "",
          "subject": "MAQUINAS, HERRAMIENTAS Y ACCESORIOS",
          "acd": 2,
          "ape": 3,
          "aa": 1,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c6-practicas-pre-profesionales-i-vinculacion-65",
          "cycle": 6,
          "group": "6",
          "code": "",
          "subject": "PR\u00c1CTICAS PRE PROFESIONALES I (VINCULACI\u00d3N)",
          "acd": 0,
          "ape": 1,
          "aa": 0,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c7-practicas-pre-profesionales-ii-laborales-1-73",
          "cycle": 7,
          "group": "N7",
          "code": "",
          "subject": "PR\u00c1CTICAS PRE PROFESIONALES II (LABORALES 1",
          "acd": 0,
          "ape": 0,
          "aa": 1,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c8-practicas-pre-profesionales-iii-laborales-2-83",
          "cycle": 8,
          "group": "N8",
          "code": "",
          "subject": "PR\u00c1CTICAS PRE PROFESIONALES III (LABORALES 2)",
          "acd": 0,
          "ape": 1,
          "aa": 5,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c9-practicas-pre-profesionales-iv-laborales-3-92",
          "cycle": 9,
          "group": "N9",
          "code": "",
          "subject": "PR\u00c1CTICAS PRE PROFESIONALES IV(LABORALES 3)",
          "acd": 0,
          "ape": 1,
          "aa": 0,
          "offer": 26,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "otilia-cordero",
      "nro": 20,
      "name": "OTILIA CORDERO",
      "title": "Economista",
      "formation": "PhD",
      "type": "Docente",
      "modality": "Ocasional",
      "belonging": "Docente compartido",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/default-profile.png",
      "subjects": [
        {
          "id": "c6-economia-general-59",
          "cycle": 6,
          "group": "6",
          "code": "",
          "subject": "ECONOM\u00cdA GENERAL",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c7-marketing-70",
          "cycle": 7,
          "group": "N7",
          "code": "",
          "subject": "MARKETING",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c9-gestion-financiera-91",
          "cycle": 9,
          "group": "N9",
          "code": "",
          "subject": "GESTI\u00d3N FINANCIERA",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 26,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "raul-pelaez",
      "nro": 21,
      "name": "RA\u00daL PEL\u00c1EZ",
      "title": "Ingeniero Mec\u00e1nico",
      "formation": "PhD",
      "type": "Docente",
      "modality": "Titular",
      "belonging": "Docente exclusivo Industrial",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/default-profile.png",
      "subjects": [
        {
          "id": "c7-equipo-industrial-69",
          "cycle": 7,
          "group": "N7",
          "code": "",
          "subject": "EQUIPO INDUSTRIAL",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "rojas-quinde-jenny-maritza",
      "nro": 22,
      "name": "ROJAS QUINDE JENNY MARITZA",
      "title": "Ingeniero Industrial",
      "formation": "Maestr\u00eda",
      "type": "T\u00e9cnico docente",
      "modality": "Ocasional",
      "belonging": "Docente exclusivo Industrial",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/ing-rojas-quinde-jenny-maritza-ms.jpg",
      "subjects": [
        {
          "id": "c6-investigacion-y-desarrollo-de-nuevos-productos-p1-61",
          "cycle": 6,
          "group": "6",
          "code": "",
          "subject": "INVESTIGACI\u00d3N Y DESARROLLO DE NUEVOS PRODUCTOS P1",
          "acd": 3,
          "ape": 2,
          "aa": 4,
          "offer": 16,
          "role": "Pr\u00e1cticas"
        },
        {
          "id": "c6-investigacion-y-desarrollo-de-nuevos-productos-p2-62",
          "cycle": 6,
          "group": "6",
          "code": "",
          "subject": "INVESTIGACI\u00d3N Y DESARROLLO DE NUEVOS PRODUCTOS P2",
          "acd": 3,
          "ape": 2,
          "aa": 4,
          "offer": 16,
          "role": "Pr\u00e1cticas"
        }
      ]
    },
    {
      "id": "sanchez-alvarracin-carlos-mauricio",
      "nro": 23,
      "name": "S\u00c1NCHEZ ALVARRAC\u00cdN CARLOS MAURICIO",
      "title": "Ingeniero Mec\u00e1nico",
      "formation": "PhD candidate",
      "type": "Docente",
      "modality": "Ocasional",
      "belonging": "Docente compartido",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/ing-sanchez-alvarracin-carlos-mauricio-ms.jpg",
      "subjects": [
        {
          "id": "c3-ecuaciones-diferenciales-34",
          "cycle": 3,
          "group": "N3",
          "code": "19093",
          "subject": "ECUACIONES DIFERENCIALES",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "silvia-pena",
      "nro": 24,
      "name": "SILVIA PE\u00d1A",
      "title": "Ingeniero Qu\u00edmico",
      "formation": "PhD",
      "type": "Docente",
      "modality": "Ocasional",
      "belonging": "Docente compartido",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/ing-pena-gonzalez-silvia-alexandra-phd.jpg",
      "subjects": [
        {
          "id": "c5-desarrollo-de-emprendedores-49",
          "cycle": 5,
          "group": "N5",
          "code": "",
          "subject": "DESARROLLO DE EMPRENDEDORES",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c8-gestion-de-calidad-80",
          "cycle": 8,
          "group": "N8",
          "code": "",
          "subject": "GESTI\u00d3N DE CALIDAD",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "vanegas-pena-paul-fernando",
      "nro": 25,
      "name": "VANEGAS PE\u00d1A PA\u00daL FERNANDO",
      "title": "Ingeniero en sistemas",
      "formation": "PhD candidate",
      "type": "Docente",
      "modality": "Ocasional",
      "belonging": "Docente compartido",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/ing-vanegas-pena-paul-fernando-mba.jpg",
      "subjects": [
        {
          "id": "c2-lenguajes-de-programacion-23",
          "cycle": 2,
          "group": "N2",
          "code": "19034",
          "subject": "LENGUAJES DE PROGRAMACI\u00d3N",
          "acd": 4,
          "ape": 4,
          "aa": 4,
          "offer": 44,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "vintimilla-alvarez-paola-fernanda",
      "nro": 26,
      "name": "VINTIMILLA \u00c1LVAREZ PAOLA FERNANDA",
      "title": "Ingeniero Industrial",
      "formation": "PhD candidate",
      "type": "Docente",
      "modality": "Ocasional",
      "belonging": "Docente exclusivo Industrial",
      "dedication": "Tiempo completo",
      "image": "assets/faculty/ing-vintimilla-alvarez-paola-fernanda-ms.jpg",
      "subjects": [
        {
          "id": "c5-diseno-industrial-cad-51",
          "cycle": 5,
          "group": "N5",
          "code": "",
          "subject": "DISE\u00d1O INDUSTRIAL CAD",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c7-organizacion-de-la-produccion-72",
          "cycle": 7,
          "group": "N7",
          "code": "",
          "subject": "ORGANIZACI\u00d3N DE LA PRODUCCI\u00d3N",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c8-logistica-y-cadena-de-suministro-79",
          "cycle": 8,
          "group": "N8",
          "code": "",
          "subject": "LOG\u00cdSTICA Y CADENA DE SUMINISTRO",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c10-unidad-de-integracion-curricular-2-101",
          "cycle": 10,
          "group": "N10",
          "code": "",
          "subject": "UNIDAD DE INTEGRACI\u00d3N CURRICULAR 2",
          "acd": 0,
          "ape": 0,
          "aa": 1,
          "offer": 24,
          "role": "ACD"
        }
      ]
    },
    {
      "id": "por-definir",
      "name": "POR DEFINIR",
      "title": "Asignaci\u00f3n pendiente",
      "formation": "N/D",
      "type": "Por definir",
      "modality": "N/D",
      "belonging": "N/D",
      "dedication": "N/D",
      "image": "assets/faculty/default-profile.png",
      "subjects": [
        {
          "id": "c1-fisica-i-g2-15",
          "cycle": 1,
          "group": "N1 G2 PARALELO B",
          "code": "19029",
          "subject": "F\u00cdSICA I G2",
          "acd": 4,
          "ape": 4,
          "aa": 4,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c2-lenguajes-de-programacion-23",
          "cycle": 2,
          "group": "N2",
          "code": "19034",
          "subject": "LENGUAJES DE PROGRAMACI\u00d3N",
          "acd": 4,
          "ape": 4,
          "aa": 4,
          "offer": 44,
          "role": "Pr\u00e1cticas"
        },
        {
          "id": "c3-estadistica-analitica-33",
          "cycle": 3,
          "group": "N3",
          "code": "19094",
          "subject": "ESTAD\u00cdSTICA ANAL\u00cdTICA",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 44,
          "role": "Pr\u00e1cticas"
        },
        {
          "id": "c5-diseno-de-maquinas-50",
          "cycle": 5,
          "group": "N5",
          "code": "",
          "subject": "DISE\u00d1O DE M\u00c1QUINAS",
          "acd": 2,
          "ape": 2,
          "aa": 2,
          "offer": 35,
          "role": "ACD"
        },
        {
          "id": "c8-gestion-de-calidad-80",
          "cycle": 8,
          "group": "N8",
          "code": "",
          "subject": "GESTI\u00d3N DE CALIDAD",
          "acd": 3,
          "ape": 3,
          "aa": 3,
          "offer": 35,
          "role": "Pr\u00e1cticas"
        }
      ]
    }
  ],
  "courses": [
    {
      "id": "c1-quimica-general-g1-6",
      "row": 6,
      "cycle": 1,
      "group": "N1 G1 PARALELO A",
      "code": "19029",
      "subject": "QU\u00cdMICA GENERAL G1",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 35,
      "teacher": "\u00cd\u00d1IGUEZ MOR\u00c1N ANDREA MAR\u00cdA",
      "practiceTeachers": []
    },
    {
      "id": "c1-metodologia-de-la-investigacion-g1-7",
      "row": 7,
      "cycle": 1,
      "group": "N1 G1 PARALELO A",
      "code": "19028",
      "subject": "METODOLOG\u00cdA DE LA INVESTIGACI\u00d3N G1",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 35,
      "teacher": "FLORES SIGUENZA PABLO ANDR\u00c9S",
      "practiceTeachers": []
    },
    {
      "id": "c1-fisica-i-g1-8",
      "row": 8,
      "cycle": 1,
      "group": "N1 G1 PARALELO A",
      "code": "19027",
      "subject": "F\u00cdSICA I G1",
      "acd": 4,
      "ape": 4,
      "aa": 4,
      "offer": 35,
      "teacher": "MEJ\u00cdA GUAM\u00c1N CHRISTIAN FERNANDO",
      "practiceTeachers": []
    },
    {
      "id": "c1-calculo-diferencial-g1-9",
      "row": 9,
      "cycle": 1,
      "group": "N1 G1 PARALELO A",
      "code": "19026",
      "subject": "C\u00c1LCULO DIFERENCIAL G1",
      "acd": 3,
      "ape": 4,
      "aa": 2,
      "offer": 35,
      "teacher": "NARVAEZ BUEST\u00c1N FREDDY EDUARDO",
      "practiceTeachers": []
    },
    {
      "id": "c1-algebra-lineal-g1-10",
      "row": 10,
      "cycle": 1,
      "group": "N1 G1 PARALELO A",
      "code": "19025",
      "subject": "\u00c1LGEBRA LINEAL G1",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 35,
      "teacher": "GUAM\u00c1N ORTIZ FRANKLIN EDUARDO",
      "practiceTeachers": []
    },
    {
      "id": "c1-calculo-diferencial-g2-14",
      "row": 14,
      "cycle": 1,
      "group": "N1 G2 PARALELO B",
      "code": "19026",
      "subject": "C\u00c1LCULO DIFERENCIAL G2",
      "acd": 3,
      "ape": 4,
      "aa": 2,
      "offer": 35,
      "teacher": "GUAM\u00c1N ORTIZ FRANKLIN EDUARDO",
      "practiceTeachers": []
    },
    {
      "id": "c1-fisica-i-g2-15",
      "row": 15,
      "cycle": 1,
      "group": "N1 G2 PARALELO B",
      "code": "19029",
      "subject": "F\u00cdSICA I G2",
      "acd": 4,
      "ape": 4,
      "aa": 4,
      "offer": 35,
      "teacher": "POR DEFINIR",
      "practiceTeachers": []
    },
    {
      "id": "c1-algebra-lineal-g2-16",
      "row": 16,
      "cycle": 1,
      "group": "N1 G2 PARALELO B",
      "code": "19025",
      "subject": "\u00c1LGEBRA LINEAL G2",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 35,
      "teacher": "GUAM\u00c1N ORTIZ FRANKLIN EDUARDO",
      "practiceTeachers": []
    },
    {
      "id": "c1-quimica-general-g2-17",
      "row": 17,
      "cycle": 1,
      "group": "N1 G2 PARALELO B",
      "code": "19029",
      "subject": "QU\u00cdMICA GENERAL G2",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 35,
      "teacher": "\u00cd\u00d1IGUEZ MOR\u00c1N ANDREA MAR\u00cdA",
      "practiceTeachers": []
    },
    {
      "id": "c2-quimica-organica-22",
      "row": 22,
      "cycle": 2,
      "group": "N2",
      "code": "19856",
      "subject": "QU\u00cdMICA ORG\u00c1NICA",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 44,
      "teacher": "\u00cd\u00d1IGUEZ MOR\u00c1N ANDREA MAR\u00cdA",
      "practiceTeachers": [
        "FREDDY BUSTAMANTE"
      ]
    },
    {
      "id": "c2-lenguajes-de-programacion-23",
      "row": 23,
      "cycle": 2,
      "group": "N2",
      "code": "19034",
      "subject": "LENGUAJES DE PROGRAMACI\u00d3N",
      "acd": 4,
      "ape": 4,
      "aa": 4,
      "offer": 44,
      "teacher": "VANEGAS PE\u00d1A PA\u00daL FERNANDO",
      "practiceTeachers": [
        "POR DEFINIR"
      ]
    },
    {
      "id": "c2-introduccion-a-la-ingenieria-industrial-24",
      "row": 24,
      "cycle": 2,
      "group": "N2",
      "code": "19033",
      "subject": "INTRODUCCI\u00d3N A LA INGENIER\u00cdA INDUSTRIAL",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 44,
      "teacher": "\u00c1LVAREZ PALOMEQUE LOURDES XIMENA",
      "practiceTeachers": []
    },
    {
      "id": "c2-fisica-ii-25",
      "row": 25,
      "cycle": 2,
      "group": "N2",
      "code": "19032",
      "subject": "F\u00cdSICA II",
      "acd": 3,
      "ape": 4,
      "aa": 2,
      "offer": 44,
      "teacher": "MEJ\u00cdA GUAM\u00c1N CHRISTIAN FERNANDO",
      "practiceTeachers": []
    },
    {
      "id": "c2-calculo-integral-26",
      "row": 26,
      "cycle": 2,
      "group": "N2",
      "code": "19031",
      "subject": "C\u00c1LCULO INTEGRAL",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 44,
      "teacher": "FLORES SIGUENZA PABLO ANDR\u00c9S",
      "practiceTeachers": []
    },
    {
      "id": "c3-termodinamica-30",
      "row": 30,
      "cycle": 3,
      "group": "N3",
      "code": "19097",
      "subject": "TERMODIN\u00c1MICA",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 35,
      "teacher": "MEJ\u00cdA GUAM\u00c1N CHRISTIAN FERNANDO",
      "practiceTeachers": []
    },
    {
      "id": "c3-mecanica-de-materiales-31",
      "row": 31,
      "cycle": 3,
      "group": "N3",
      "code": "19096",
      "subject": "MEC\u00c1NICA DE MATERIALES",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 35,
      "teacher": "\u00c1LVAREZ LLORET \u00c9DGAR PA\u00daL",
      "practiceTeachers": []
    },
    {
      "id": "c3-ingenieria-y-tecnologia-electricas-32",
      "row": 32,
      "cycle": 3,
      "group": "N3",
      "code": "19095",
      "subject": "INGENIER\u00cdA Y TECNOLOG\u00cdA EL\u00c9CTRICAS",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 40,
      "teacher": "GUAM\u00c1N ORTIZ FRANKLIN EDUARDO",
      "practiceTeachers": []
    },
    {
      "id": "c3-estadistica-analitica-33",
      "row": 33,
      "cycle": 3,
      "group": "N3",
      "code": "19094",
      "subject": "ESTAD\u00cdSTICA ANAL\u00cdTICA",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 44,
      "teacher": "GUAMAN GUACHICHULLCA NO\u00c9 RODRIGO",
      "practiceTeachers": [
        "POR DEFINIR"
      ]
    },
    {
      "id": "c3-ecuaciones-diferenciales-34",
      "row": 34,
      "cycle": 3,
      "group": "N3",
      "code": "19093",
      "subject": "ECUACIONES DIFERENCIALES",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 35,
      "teacher": "S\u00c1NCHEZ ALVARRAC\u00cdN CARLOS MAURICIO",
      "practiceTeachers": []
    },
    {
      "id": "c4-transferencia-de-calor-38",
      "row": 38,
      "cycle": 4,
      "group": "N4",
      "code": "",
      "subject": "TRANSFERENCIA DE CALOR",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 35,
      "teacher": "NARVAEZ BUEST\u00c1N FREDDY EDUARDO",
      "practiceTeachers": []
    },
    {
      "id": "c4-tecnologia-de-materiales-39",
      "row": 39,
      "cycle": 4,
      "group": "N4",
      "code": "",
      "subject": "TECNOLOG\u00cdA DE MATERIALES",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 35,
      "teacher": "\u00c1LVAREZ LLORET \u00c9DGAR PA\u00daL",
      "practiceTeachers": []
    },
    {
      "id": "c4-transporte-de-fluidos-40",
      "row": 40,
      "cycle": 4,
      "group": "N4",
      "code": "",
      "subject": "TRANSPORTE DE FLUIDOS",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 35,
      "teacher": "GUANUCHI QUITO ALEXANDRA ELIZABETH",
      "practiceTeachers": []
    },
    {
      "id": "c4-contabilidad-41",
      "row": 41,
      "cycle": 4,
      "group": "N4",
      "code": "",
      "subject": "CONTABILIDAD",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 35,
      "teacher": "MATEO COELLO",
      "practiceTeachers": []
    },
    {
      "id": "c4-tecnicas-de-inferencia-estadistica-42",
      "row": 42,
      "cycle": 4,
      "group": "N4",
      "code": "",
      "subject": "T\u00c9CNICAS DE INFERENCIA ESTAD\u00cdSTICA",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 35,
      "teacher": "LLIVISACA VILLAZHA\u00d1AY JUAN CARLOS",
      "practiceTeachers": []
    },
    {
      "id": "c4-metodos-numericos-43",
      "row": 43,
      "cycle": 4,
      "group": "N4",
      "code": "",
      "subject": "M\u00c9TODOS NUM\u00c9RICOS",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 35,
      "teacher": "NARVAEZ BUEST\u00c1N FREDDY EDUARDO",
      "practiceTeachers": []
    },
    {
      "id": "c5-costos-y-presupuestos-de-produccion-48",
      "row": 48,
      "cycle": 5,
      "group": "N5",
      "code": "",
      "subject": "COSTOS Y PRESUPUESTOS DE PRODUCCI\u00d3N",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 35,
      "teacher": "MATEO COELLO",
      "practiceTeachers": []
    },
    {
      "id": "c5-desarrollo-de-emprendedores-49",
      "row": 49,
      "cycle": 5,
      "group": "N5",
      "code": "",
      "subject": "DESARROLLO DE EMPRENDEDORES",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 35,
      "teacher": "SILVIA PE\u00d1A",
      "practiceTeachers": []
    },
    {
      "id": "c5-diseno-de-maquinas-50",
      "row": 50,
      "cycle": 5,
      "group": "N5",
      "code": "",
      "subject": "DISE\u00d1O DE M\u00c1QUINAS",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 35,
      "teacher": "POR DEFINIR",
      "practiceTeachers": []
    },
    {
      "id": "c5-diseno-industrial-cad-51",
      "row": 51,
      "cycle": 5,
      "group": "N5",
      "code": "",
      "subject": "DISE\u00d1O INDUSTRIAL CAD",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 35,
      "teacher": "VINTIMILLA \u00c1LVAREZ PAOLA FERNANDA",
      "practiceTeachers": []
    },
    {
      "id": "c5-etica-de-la-ciencia-52",
      "row": 52,
      "cycle": 5,
      "group": "N5",
      "code": "",
      "subject": "\u00c9TICA DE LA CIENCIA",
      "acd": 1,
      "ape": 1,
      "aa": 1,
      "offer": 35,
      "teacher": "JERVES MORA RODRIGO SA\u00daL",
      "practiceTeachers": []
    },
    {
      "id": "c5-ingenieria-de-procesos-y-ergonomia-53",
      "row": 53,
      "cycle": 5,
      "group": "N5",
      "code": "",
      "subject": "INGENIER\u00cdA DE PROCESOS Y ERGONOM\u00cdA",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 35,
      "teacher": "\u00c1LVAREZ PALOMEQUE LOURDES XIMENA",
      "practiceTeachers": []
    },
    {
      "id": "c5-psicologia-industrial-54",
      "row": 54,
      "cycle": 5,
      "group": "N5",
      "code": "",
      "subject": "PSICOLOG\u00cdA INDUSTRIAL",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 35,
      "teacher": "JERVES MORA RODRIGO SA\u00daL",
      "practiceTeachers": []
    },
    {
      "id": "c6-maquinas-herramientas-y-accesorios-58",
      "row": 58,
      "cycle": 6,
      "group": "6",
      "code": "",
      "subject": "MAQUINAS, HERRAMIENTAS Y ACCESORIOS",
      "acd": 2,
      "ape": 3,
      "aa": 1,
      "offer": 35,
      "teacher": "NARVAEZ BUEST\u00c1N FREDDY EDUARDO",
      "practiceTeachers": []
    },
    {
      "id": "c6-economia-general-59",
      "row": 59,
      "cycle": 6,
      "group": "6",
      "code": "",
      "subject": "ECONOM\u00cdA GENERAL",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 35,
      "teacher": "OTILIA CORDERO",
      "practiceTeachers": []
    },
    {
      "id": "c6-gestion-del-talento-humano-60",
      "row": 60,
      "cycle": 6,
      "group": "6",
      "code": "",
      "subject": "GESTI\u00d3N DEL TALENTO HUMANO",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 35,
      "teacher": "JERVES MORA RODRIGO SA\u00daL",
      "practiceTeachers": []
    },
    {
      "id": "c6-investigacion-y-desarrollo-de-nuevos-productos-p1-61",
      "row": 61,
      "cycle": 6,
      "group": "6",
      "code": "",
      "subject": "INVESTIGACI\u00d3N Y DESARROLLO DE NUEVOS PRODUCTOS P1",
      "acd": 3,
      "ape": 2,
      "aa": 4,
      "offer": 16,
      "teacher": "GUAMAN GUACHICHULLCA NO\u00c9 RODRIGO",
      "practiceTeachers": [
        "ROJAS QUINDE JENNY MARITZA"
      ]
    },
    {
      "id": "c6-investigacion-y-desarrollo-de-nuevos-productos-p2-62",
      "row": 62,
      "cycle": 6,
      "group": "6",
      "code": "",
      "subject": "INVESTIGACI\u00d3N Y DESARROLLO DE NUEVOS PRODUCTOS P2",
      "acd": 3,
      "ape": 2,
      "aa": 4,
      "offer": 16,
      "teacher": "GUAMAN GUACHICHULLCA NO\u00c9 RODRIGO",
      "practiceTeachers": [
        "ROJAS QUINDE JENNY MARITZA"
      ]
    },
    {
      "id": "c6-investigacion-operativa-63",
      "row": 63,
      "cycle": 6,
      "group": "6",
      "code": "",
      "subject": "INVESTIGACI\u00d3N OPERATIVA",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 35,
      "teacher": "JAD\u00c1N AVIL\u00c9S DIANA CAROLINA",
      "practiceTeachers": []
    },
    {
      "id": "c6-legislacion-ecuatoriana-64",
      "row": 64,
      "cycle": 6,
      "group": "6",
      "code": "",
      "subject": "LEGISLACI\u00d3N ECUATORIANA",
      "acd": 1,
      "ape": 1,
      "aa": 1,
      "offer": 35,
      "teacher": "MATEO COELLO",
      "practiceTeachers": []
    },
    {
      "id": "c6-practicas-pre-profesionales-i-vinculacion-65",
      "row": 65,
      "cycle": 6,
      "group": "6",
      "code": "",
      "subject": "PR\u00c1CTICAS PRE PROFESIONALES I (VINCULACI\u00d3N)",
      "acd": 0,
      "ape": 1,
      "aa": 0,
      "offer": 35,
      "teacher": "NARVAEZ BUEST\u00c1N FREDDY EDUARDO",
      "practiceTeachers": []
    },
    {
      "id": "c7-equipo-industrial-69",
      "row": 69,
      "cycle": 7,
      "group": "N7",
      "code": "",
      "subject": "EQUIPO INDUSTRIAL",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 35,
      "teacher": "RA\u00daL PEL\u00c1EZ",
      "practiceTeachers": []
    },
    {
      "id": "c7-marketing-70",
      "row": 70,
      "cycle": 7,
      "group": "N7",
      "code": "",
      "subject": "MARKETING",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 35,
      "teacher": "OTILIA CORDERO",
      "practiceTeachers": []
    },
    {
      "id": "c7-matematica-financiera-71",
      "row": 71,
      "cycle": 7,
      "group": "N7",
      "code": "",
      "subject": "MATEM\u00c1TICA FINANCIERA",
      "acd": 2,
      "ape": 1,
      "aa": 3,
      "offer": 35,
      "teacher": "MATEO COELLO",
      "practiceTeachers": []
    },
    {
      "id": "c7-organizacion-de-la-produccion-72",
      "row": 72,
      "cycle": 7,
      "group": "N7",
      "code": "",
      "subject": "ORGANIZACI\u00d3N DE LA PRODUCCI\u00d3N",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 35,
      "teacher": "VINTIMILLA \u00c1LVAREZ PAOLA FERNANDA",
      "practiceTeachers": []
    },
    {
      "id": "c7-practicas-pre-profesionales-ii-laborales-1-73",
      "row": 73,
      "cycle": 7,
      "group": "N7",
      "code": "",
      "subject": "PR\u00c1CTICAS PRE PROFESIONALES II (LABORALES 1",
      "acd": 0,
      "ape": 0,
      "aa": 1,
      "offer": 35,
      "teacher": "NARVAEZ BUEST\u00c1N FREDDY EDUARDO",
      "practiceTeachers": []
    },
    {
      "id": "c7-seguridad-y-salud-ocupacional-74",
      "row": 74,
      "cycle": 7,
      "group": "N7",
      "code": "",
      "subject": "SEGURIDAD Y SALUD OCUPACIONAL",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 35,
      "teacher": "ESPINOZA HERN\u00c1NDEZ PAULINA REBECA",
      "practiceTeachers": []
    },
    {
      "id": "c7-tecnologia-energetica-75",
      "row": 75,
      "cycle": 7,
      "group": "N7",
      "code": "",
      "subject": "TECNOLOG\u00cdA ENERG\u00c9TICA",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 35,
      "teacher": "ANDRES MONTERO",
      "practiceTeachers": []
    },
    {
      "id": "c8-sistemas-de-control-de-la-produccion-78",
      "row": 78,
      "cycle": 8,
      "group": "N8",
      "code": "",
      "subject": "SISTEMAS DE CONTROL DE LA PRODUCCI\u00d3N",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 35,
      "teacher": "FLORES SIGUENZA PABLO ANDR\u00c9S",
      "practiceTeachers": []
    },
    {
      "id": "c8-logistica-y-cadena-de-suministro-79",
      "row": 79,
      "cycle": 8,
      "group": "N8",
      "code": "",
      "subject": "LOG\u00cdSTICA Y CADENA DE SUMINISTRO",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 35,
      "teacher": "VINTIMILLA \u00c1LVAREZ PAOLA FERNANDA",
      "practiceTeachers": []
    },
    {
      "id": "c8-gestion-de-calidad-80",
      "row": 80,
      "cycle": 8,
      "group": "N8",
      "code": "",
      "subject": "GESTI\u00d3N DE CALIDAD",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 35,
      "teacher": "SILVIA PE\u00d1A",
      "practiceTeachers": [
        "POR DEFINIR"
      ]
    },
    {
      "id": "c8-gestion-ambiental-empresarial-81",
      "row": 81,
      "cycle": 8,
      "group": "N8",
      "code": "",
      "subject": "GESTI\u00d3N AMBIENTAL EMPRESARIAL",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 35,
      "teacher": "\u00c1LVAREZ PALOMEQUE LOURDES XIMENA",
      "practiceTeachers": []
    },
    {
      "id": "c8-ingenieria-del-mantenimiento-82",
      "row": 82,
      "cycle": 8,
      "group": "N8",
      "code": "",
      "subject": "INGENIER\u00cdA DEL MANTENIMIENTO",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 35,
      "teacher": "\u00c1LVAREZ LLORET \u00c9DGAR PA\u00daL",
      "practiceTeachers": []
    },
    {
      "id": "c8-practicas-pre-profesionales-iii-laborales-2-83",
      "row": 83,
      "cycle": 8,
      "group": "N8",
      "code": "",
      "subject": "PR\u00c1CTICAS PRE PROFESIONALES III (LABORALES 2)",
      "acd": 0,
      "ape": 1,
      "aa": 5,
      "offer": 35,
      "teacher": "NARVAEZ BUEST\u00c1N FREDDY EDUARDO",
      "practiceTeachers": []
    },
    {
      "id": "c9-lean-manufacturing-y-6-sigma-i-86",
      "row": 86,
      "cycle": 9,
      "group": "N9",
      "code": "",
      "subject": "LEAN MANUFACTURING Y 6 SIGMA (I)",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 16,
      "teacher": "LLIVISACA VILLAZHA\u00d1AY JUAN CARLOS",
      "practiceTeachers": []
    },
    {
      "id": "c9-lean-services-y-sigma-sigma-i-87",
      "row": 87,
      "cycle": 9,
      "group": "N9",
      "code": "",
      "subject": "LEAN SERVICES Y SIGMA SIGMA (I)",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 6,
      "teacher": "BARRAG\u00c1N LANDY MILTON FRANCISCO",
      "practiceTeachers": []
    },
    {
      "id": "c9-instrumentacion-y-control-88",
      "row": 88,
      "cycle": 9,
      "group": "N9",
      "code": "",
      "subject": "INSTRUMENTACI\u00d3N Y CONTROL",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 26,
      "teacher": "FLORES SIGUENZA PABLO ANDR\u00c9S",
      "practiceTeachers": []
    },
    {
      "id": "c9-diseno-experimental-89",
      "row": 89,
      "cycle": 9,
      "group": "N9",
      "code": "",
      "subject": "DISE\u00d1O EXPERIMENTAL",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 26,
      "teacher": "LLIVISACA VILLAZHA\u00d1AY JUAN CARLOS",
      "practiceTeachers": []
    },
    {
      "id": "c9-sistemas-de-informacion-estrategica-90",
      "row": 90,
      "cycle": 9,
      "group": "N9",
      "code": "",
      "subject": "SISTEMAS DE INFORMACI\u00d3N ESTRAT\u00c9GICA",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 26,
      "teacher": "MATEO COELLO",
      "practiceTeachers": []
    },
    {
      "id": "c9-gestion-financiera-91",
      "row": 91,
      "cycle": 9,
      "group": "N9",
      "code": "",
      "subject": "GESTI\u00d3N FINANCIERA",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 26,
      "teacher": "OTILIA CORDERO",
      "practiceTeachers": []
    },
    {
      "id": "c9-practicas-pre-profesionales-iv-laborales-3-92",
      "row": 92,
      "cycle": 9,
      "group": "N9",
      "code": "",
      "subject": "PR\u00c1CTICAS PRE PROFESIONALES IV(LABORALES 3)",
      "acd": 0,
      "ape": 1,
      "aa": 0,
      "offer": 26,
      "teacher": "NARVAEZ BUEST\u00c1N FREDDY EDUARDO",
      "practiceTeachers": []
    },
    {
      "id": "c9-unidad-de-integracion-curricular-1-93",
      "row": 93,
      "cycle": 9,
      "group": "N9",
      "code": "",
      "subject": "UNIDAD DE INTEGRACI\u00d3N CURRICULAR 1",
      "acd": 0,
      "ape": 1,
      "aa": 5,
      "offer": 26,
      "teacher": "JAD\u00c1N AVIL\u00c9S DIANA CAROLINA",
      "practiceTeachers": []
    },
    {
      "id": "c10-diseno-y-gestion-de-proyectos-96",
      "row": 96,
      "cycle": 10,
      "group": "N10",
      "code": "",
      "subject": "DISE\u00d1O Y GESTI\u00d3N DE PROYECTOS",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 24,
      "teacher": "MATEO COELLO",
      "practiceTeachers": []
    },
    {
      "id": "c10-gestion-estrategica-97",
      "row": 97,
      "cycle": 10,
      "group": "N10",
      "code": "",
      "subject": "GESTI\u00d3N ESTRAT\u00c9GICA",
      "acd": 2,
      "ape": 2,
      "aa": 2,
      "offer": 24,
      "teacher": "MATEO COELLO",
      "practiceTeachers": []
    },
    {
      "id": "c10-lean-manufacturing-y-six-sigma-ii-i1-98",
      "row": 98,
      "cycle": 10,
      "group": "N10",
      "code": "",
      "subject": "LEAN MANUFACTURING Y SIX SIGMA (II) I1",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 24,
      "teacher": "LLIVISACA VILLAZHA\u00d1AY JUAN CARLOS",
      "practiceTeachers": []
    },
    {
      "id": "c10-innovation-management-99",
      "row": 99,
      "cycle": 10,
      "group": "N10",
      "code": "",
      "subject": "INNOVATION MANAGEMENT",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 24,
      "teacher": "BARRAG\u00c1N LANDY MILTON FRANCISCO",
      "practiceTeachers": []
    },
    {
      "id": "c10-simulacion-de-la-produccion-100",
      "row": 100,
      "cycle": 10,
      "group": "N10",
      "code": "",
      "subject": "SIMULACI\u00d3N DE LA PRODUCCI\u00d3N",
      "acd": 3,
      "ape": 3,
      "aa": 3,
      "offer": 24,
      "teacher": "JAMES ARIAS",
      "practiceTeachers": []
    },
    {
      "id": "c10-unidad-de-integracion-curricular-2-101",
      "row": 101,
      "cycle": 10,
      "group": "N10",
      "code": "",
      "subject": "UNIDAD DE INTEGRACI\u00d3N CURRICULAR 2",
      "acd": 0,
      "ape": 0,
      "aa": 1,
      "offer": 24,
      "teacher": "VINTIMILLA \u00c1LVAREZ PAOLA FERNANDA",
      "practiceTeachers": []
    }
  ]
};
