const syllabiData = {
  "summary": {
    "source": "C:\\Users\\Usuario\\Downloads\\SILABOS-20260827T153658Z-1-001\\SILABOS",
    "count": 62,
    "totalOriginalSize": 124726608,
    "totalSize": 124683289,
    "savedBytes": 43319,
    "levels": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ]
  },
  "items": [
    {
      "id": "n10-silabo-diseno-y-gestion-de-proyectos",
      "level": 10,
      "itinerary": "",
      "title": "DISEÑO Y GESTIÓN DE PROYECTOS",
      "sourceName": "DISEÑO Y GESTIÓN DE PROYECTOS.pdf",
      "path": "assets/syllabi/docs/n10-silabo-diseno-y-gestion-de-proyectos.pdf",
      "pages": 3,
      "originalSize": 1843320,
      "size": 1842646,
      "optimized": true
    },
    {
      "id": "n10-silabo-gestion-estrategica",
      "level": 10,
      "itinerary": "",
      "title": "GESTIÓN ESTRATÉGICA",
      "sourceName": "GESTIÓN ESTRATÉGICA.pdf",
      "path": "assets/syllabi/docs/n10-silabo-gestion-estrategica.pdf",
      "pages": 3,
      "originalSize": 1844914,
      "size": 1844240,
      "optimized": true
    },
    {
      "id": "n10-itinerario-manufacturing-lean-manufacturing-y-six-sigma-ii-i1",
      "level": 10,
      "itinerary": "Itinerario Manufacturing",
      "title": "LEAN MANUFACTURING Y SIX SIGMA (II) I1",
      "sourceName": "LEAN MANUFACTURING Y SIX SIGMA (II) I1.pdf",
      "path": "assets/syllabi/docs/n10-itinerario-manufacturing-lean-manufacturing-y-six-sigma-ii-i1.pdf",
      "pages": 3,
      "originalSize": 2384915,
      "size": 2384185,
      "optimized": true
    },
    {
      "id": "n10-itinerario-servicios-innovation-management-i2",
      "level": 10,
      "itinerary": "Itinerario Servicios",
      "title": "INNOVATION MANAGEMENT I2",
      "sourceName": "INNOVATION MANAGEMENT I2.pdf",
      "path": "assets/syllabi/docs/n10-itinerario-servicios-innovation-management-i2.pdf",
      "pages": 3,
      "originalSize": 1842776,
      "size": 1842102,
      "optimized": true
    },
    {
      "id": "n10-silabo-simulacion-de-la-produccion",
      "level": 10,
      "itinerary": "",
      "title": "SIMULACIÓN DE LA PRODUCCIÓN",
      "sourceName": "SIMULACIÓN DE LA PRODUCCIÓN.pdf",
      "path": "assets/syllabi/docs/n10-silabo-simulacion-de-la-produccion.pdf",
      "pages": 3,
      "originalSize": 1844961,
      "size": 1844287,
      "optimized": true
    },
    {
      "id": "n10-silabo-unidad-de-integracion-curricular-2",
      "level": 10,
      "itinerary": "",
      "title": "UNIDAD DE INTEGRACIÓN CURRICULAR 2",
      "sourceName": "UNIDAD DE INTEGRACIÓN CURRICULAR 2.pdf",
      "path": "assets/syllabi/docs/n10-silabo-unidad-de-integracion-curricular-2.pdf",
      "pages": 3,
      "originalSize": 2384367,
      "size": 2383637,
      "optimized": true
    },
    {
      "id": "n1-silabo-algebra-lineal",
      "level": 1,
      "itinerary": "",
      "title": "ALGEBRA LINEAL",
      "sourceName": "ALGEBRA LINEAL.pdf",
      "path": "assets/syllabi/docs/n1-silabo-algebra-lineal.pdf",
      "pages": 3,
      "originalSize": 2385667,
      "size": 2384941,
      "optimized": true
    },
    {
      "id": "n1-silabo-calculo-diferencial",
      "level": 1,
      "itinerary": "",
      "title": "CALCULO DIFERENCIAL",
      "sourceName": "CALCULO DIFERENCIAL.pdf",
      "path": "assets/syllabi/docs/n1-silabo-calculo-diferencial.pdf",
      "pages": 3,
      "originalSize": 1842571,
      "size": 1841897,
      "optimized": true
    },
    {
      "id": "n1-silabo-fisica-1",
      "level": 1,
      "itinerary": "",
      "title": "FISICA 1",
      "sourceName": "FISICA 1.pdf",
      "path": "assets/syllabi/docs/n1-silabo-fisica-1.pdf",
      "pages": 3,
      "originalSize": 1844253,
      "size": 1843579,
      "optimized": true
    },
    {
      "id": "n1-silabo-metodologia-de-la-investigacion",
      "level": 1,
      "itinerary": "",
      "title": "METODOLOGIA DE LA INVESTIGACION",
      "sourceName": "METODOLOGIA DE LA INVESTIGACION.pdf",
      "path": "assets/syllabi/docs/n1-silabo-metodologia-de-la-investigacion.pdf",
      "pages": 3,
      "originalSize": 1842958,
      "size": 1842284,
      "optimized": true
    },
    {
      "id": "n1-silabo-quimica-general",
      "level": 1,
      "itinerary": "",
      "title": "QUIMICA GENERAL",
      "sourceName": "QUIMICA GENERAL.pdf",
      "path": "assets/syllabi/docs/n1-silabo-quimica-general.pdf",
      "pages": 3,
      "originalSize": 1844553,
      "size": 1843879,
      "optimized": true
    },
    {
      "id": "n2-silabo-calculo-integral",
      "level": 2,
      "itinerary": "",
      "title": "CALCULO INTEGRAL",
      "sourceName": "CALCULO INTEGRAL.pdf",
      "path": "assets/syllabi/docs/n2-silabo-calculo-integral.pdf",
      "pages": 3,
      "originalSize": 1841664,
      "size": 1840990,
      "optimized": true
    },
    {
      "id": "n2-silabo-fisica-ii",
      "level": 2,
      "itinerary": "",
      "title": "FISICA II",
      "sourceName": "FISICA II.pdf",
      "path": "assets/syllabi/docs/n2-silabo-fisica-ii.pdf",
      "pages": 3,
      "originalSize": 1844737,
      "size": 1844063,
      "optimized": true
    },
    {
      "id": "n2-silabo-introduccion-a-la-ingenieria-industrial",
      "level": 2,
      "itinerary": "",
      "title": "INTRODUCCIÓN A LA INGENIERÍA INDUSTRIAL",
      "sourceName": "INTRODUCCIÓN A LA INGENIERÍA INDUSTRIAL.pdf",
      "path": "assets/syllabi/docs/n2-silabo-introduccion-a-la-ingenieria-industrial.pdf",
      "pages": 3,
      "originalSize": 1842855,
      "size": 1842181,
      "optimized": true
    },
    {
      "id": "n2-silabo-lenguajes-de-programacion",
      "level": 2,
      "itinerary": "",
      "title": "LENGUAJES DE PROGRAMACION",
      "sourceName": "LENGUAJES DE PROGRAMACION.pdf",
      "path": "assets/syllabi/docs/n2-silabo-lenguajes-de-programacion.pdf",
      "pages": 3,
      "originalSize": 1842649,
      "size": 1841975,
      "optimized": true
    },
    {
      "id": "n2-silabo-quimica-organica",
      "level": 2,
      "itinerary": "",
      "title": "QUIMICA ORGANICA",
      "sourceName": "QUIMICA ORGANICA.pdf",
      "path": "assets/syllabi/docs/n2-silabo-quimica-organica.pdf",
      "pages": 3,
      "originalSize": 1842387,
      "size": 1841713,
      "optimized": true
    },
    {
      "id": "n3-silabo-ecuaciones-diferenciales",
      "level": 3,
      "itinerary": "",
      "title": "ECUACIONES DIFERENCIALES",
      "sourceName": "ECUACIONES DIFERENCIALES.pdf",
      "path": "assets/syllabi/docs/n3-silabo-ecuaciones-diferenciales.pdf",
      "pages": 3,
      "originalSize": 1844006,
      "size": 1843332,
      "optimized": true
    },
    {
      "id": "n3-silabo-estadistica-analitica",
      "level": 3,
      "itinerary": "",
      "title": "ESTADISTICA ANALITICA",
      "sourceName": "ESTADISTICA ANALITICA.pdf",
      "path": "assets/syllabi/docs/n3-silabo-estadistica-analitica.pdf",
      "pages": 3,
      "originalSize": 2383462,
      "size": 2382732,
      "optimized": true
    },
    {
      "id": "n3-silabo-ing-y-tecnologia-electricas",
      "level": 3,
      "itinerary": "",
      "title": "ING. Y TECNOLOGIA ELECTRICAS",
      "sourceName": "ING. Y TECNOLOGIA ELECTRICAS.pdf",
      "path": "assets/syllabi/docs/n3-silabo-ing-y-tecnologia-electricas.pdf",
      "pages": 4,
      "originalSize": 2413805,
      "size": 2413015,
      "optimized": true
    },
    {
      "id": "n3-silabo-mecanica-de-materiales",
      "level": 3,
      "itinerary": "",
      "title": "MECANICA DE MATERIALES",
      "sourceName": "MECANICA DE MATERIALES.pdf",
      "path": "assets/syllabi/docs/n3-silabo-mecanica-de-materiales.pdf",
      "pages": 3,
      "originalSize": 1843507,
      "size": 1842833,
      "optimized": true
    },
    {
      "id": "n3-silabo-termodinamica",
      "level": 3,
      "itinerary": "",
      "title": "TERMODINAMICA",
      "sourceName": "TERMODINAMICA.pdf",
      "path": "assets/syllabi/docs/n3-silabo-termodinamica.pdf",
      "pages": 4,
      "originalSize": 1874352,
      "size": 1873614,
      "optimized": true
    },
    {
      "id": "n4-silabo-contabilidad",
      "level": 4,
      "itinerary": "",
      "title": "CONTABILIDAD",
      "sourceName": "CONTABILIDAD.pdf",
      "path": "assets/syllabi/docs/n4-silabo-contabilidad.pdf",
      "pages": 3,
      "originalSize": 2385107,
      "size": 2384377,
      "optimized": true
    },
    {
      "id": "n4-silabo-metodos-numericos",
      "level": 4,
      "itinerary": "",
      "title": "MÉTODOS NUMÉRICOS",
      "sourceName": "MÉTODOS NUMÉRICOS.pdf",
      "path": "assets/syllabi/docs/n4-silabo-metodos-numericos.pdf",
      "pages": 3,
      "originalSize": 1841766,
      "size": 1841092,
      "optimized": true
    },
    {
      "id": "n4-silabo-tecnologia-de-materiales",
      "level": 4,
      "itinerary": "",
      "title": "TECNOLOGÍA DE MATERIALES",
      "sourceName": "TECNOLOGÍA DE MATERIALES.pdf",
      "path": "assets/syllabi/docs/n4-silabo-tecnologia-de-materiales.pdf",
      "pages": 3,
      "originalSize": 1844326,
      "size": 1843652,
      "optimized": true
    },
    {
      "id": "n4-silabo-transferencia-de-calor",
      "level": 4,
      "itinerary": "",
      "title": "TRANSFERENCIA DE CALOR",
      "sourceName": "TRANSFERENCIA DE CALOR.pdf",
      "path": "assets/syllabi/docs/n4-silabo-transferencia-de-calor.pdf",
      "pages": 3,
      "originalSize": 1843136,
      "size": 1842462,
      "optimized": true
    },
    {
      "id": "n4-silabo-transporte-de-fluidos",
      "level": 4,
      "itinerary": "",
      "title": "TRANSPORTE DE FLUIDOS",
      "sourceName": "TRANSPORTE DE FLUIDOS.pdf",
      "path": "assets/syllabi/docs/n4-silabo-transporte-de-fluidos.pdf",
      "pages": 3,
      "originalSize": 1842637,
      "size": 1841963,
      "optimized": true
    },
    {
      "id": "n4-silabo-tecnicas-de-inferencia-estadistica",
      "level": 4,
      "itinerary": "",
      "title": "TÉCNICAS DE INFERENCIA ESTADÍSTICA",
      "sourceName": "TÉCNICAS DE INFERENCIA ESTADÍSTICA.pdf",
      "path": "assets/syllabi/docs/n4-silabo-tecnicas-de-inferencia-estadistica.pdf",
      "pages": 3,
      "originalSize": 1842244,
      "size": 1841570,
      "optimized": true
    },
    {
      "id": "n5-silabo-costos-y-presupuestos-de-produccion",
      "level": 5,
      "itinerary": "",
      "title": "COSTOS Y PRESUPUESTOS DE PRODUCCIÓN",
      "sourceName": "COSTOS Y PRESUPUESTOS DE PRODUCCIÓN.pdf",
      "path": "assets/syllabi/docs/n5-silabo-costos-y-presupuestos-de-produccion.pdf",
      "pages": 3,
      "originalSize": 1842846,
      "size": 1842172,
      "optimized": true
    },
    {
      "id": "n5-silabo-desarrollo-de-emprendedores",
      "level": 5,
      "itinerary": "",
      "title": "DESARROLLO DE EMPRENDEDORES",
      "sourceName": "DESARROLLO DE EMPRENDEDORES.pdf",
      "path": "assets/syllabi/docs/n5-silabo-desarrollo-de-emprendedores.pdf",
      "pages": 3,
      "originalSize": 1844663,
      "size": 1843989,
      "optimized": true
    },
    {
      "id": "n5-silabo-diseno-de-maquinas",
      "level": 5,
      "itinerary": "",
      "title": "DISEÑO DE MÁQUINAS",
      "sourceName": "DISEÑO DE MÁQUINAS.pdf",
      "path": "assets/syllabi/docs/n5-silabo-diseno-de-maquinas.pdf",
      "pages": 3,
      "originalSize": 2383535,
      "size": 2382805,
      "optimized": true
    },
    {
      "id": "n5-silabo-diseno-industrial-cad",
      "level": 5,
      "itinerary": "",
      "title": "DISEÑO INDUSTRIAL CAD",
      "sourceName": "DISEÑO INDUSTRIAL CAD.pdf",
      "path": "assets/syllabi/docs/n5-silabo-diseno-industrial-cad.pdf",
      "pages": 3,
      "originalSize": 2385098,
      "size": 2384368,
      "optimized": true
    },
    {
      "id": "n5-silabo-ingenieria-de-procesos-y-ergonomia",
      "level": 5,
      "itinerary": "",
      "title": "INGENIERÍA DE PROCESOS Y ERGONOMÍA",
      "sourceName": "INGENIERÍA DE PROCESOS Y ERGONOMÍA.pdf",
      "path": "assets/syllabi/docs/n5-silabo-ingenieria-de-procesos-y-ergonomia.pdf",
      "pages": 3,
      "originalSize": 1843389,
      "size": 1842698,
      "optimized": true
    },
    {
      "id": "n5-silabo-psicologia-industrial",
      "level": 5,
      "itinerary": "",
      "title": "PSICOLOGÍA INDUSTRIAL",
      "sourceName": "PSICOLOGÍA INDUSTRIAL.pdf",
      "path": "assets/syllabi/docs/n5-silabo-psicologia-industrial.pdf",
      "pages": 3,
      "originalSize": 1845244,
      "size": 1844570,
      "optimized": true
    },
    {
      "id": "n5-silabo-etica-de-la-ciencia",
      "level": 5,
      "itinerary": "",
      "title": "ÉTICA DE LA CIENCIA",
      "sourceName": "ÉTICA DE LA CIENCIA.pdf",
      "path": "assets/syllabi/docs/n5-silabo-etica-de-la-ciencia.pdf",
      "pages": 3,
      "originalSize": 1844503,
      "size": 1843829,
      "optimized": true
    },
    {
      "id": "n6-silabo-economia-general",
      "level": 6,
      "itinerary": "",
      "title": "ECONOMÍA GENERAL",
      "sourceName": "ECONOMÍA GENERAL.pdf",
      "path": "assets/syllabi/docs/n6-silabo-economia-general.pdf",
      "pages": 3,
      "originalSize": 1843543,
      "size": 1842869,
      "optimized": true
    },
    {
      "id": "n6-silabo-gestion-del-talento-humano",
      "level": 6,
      "itinerary": "",
      "title": "GESTIÓN DEL TALENTO HUMANO",
      "sourceName": "GESTIÓN DEL TALENTO HUMANO.pdf",
      "path": "assets/syllabi/docs/n6-silabo-gestion-del-talento-humano.pdf",
      "pages": 4,
      "originalSize": 1873512,
      "size": 1872774,
      "optimized": true
    },
    {
      "id": "n6-silabo-investigacion-operativa",
      "level": 6,
      "itinerary": "",
      "title": "INVESTIGACIÓN OPERATIVA",
      "sourceName": "INVESTIGACIÓN OPERATIVA.pdf",
      "path": "assets/syllabi/docs/n6-silabo-investigacion-operativa.pdf",
      "pages": 3,
      "originalSize": 1844378,
      "size": 1843704,
      "optimized": true
    },
    {
      "id": "n6-silabo-legislacion-ecuatoriana",
      "level": 6,
      "itinerary": "",
      "title": "LEGISLACIÓN ECUATORIANA",
      "sourceName": "LEGISLACIÓN ECUATORIANA(1).pdf",
      "path": "assets/syllabi/docs/n6-silabo-legislacion-ecuatoriana.pdf",
      "pages": 3,
      "originalSize": 1844655,
      "size": 1843880,
      "optimized": true
    },
    {
      "id": "n6-silabo-legislacion-ecuatoriana-2",
      "level": 6,
      "itinerary": "",
      "title": "LEGISLACIÓN ECUATORIANA",
      "sourceName": "LEGISLACIÓN ECUATORIANA.pdf",
      "path": "assets/syllabi/docs/n6-silabo-legislacion-ecuatoriana-2.pdf",
      "pages": 3,
      "originalSize": 2385396,
      "size": 2384698,
      "optimized": true
    },
    {
      "id": "n6-silabo-maquinas-herramientas-y-accesorios",
      "level": 6,
      "itinerary": "",
      "title": "MÁQUINAS, HERRAMIENTAS Y ACCESORIOS",
      "sourceName": "MÁQUINAS, HERRAMIENTAS Y ACCESORIOS.pdf",
      "path": "assets/syllabi/docs/n6-silabo-maquinas-herramientas-y-accesorios.pdf",
      "pages": 3,
      "originalSize": 2385100,
      "size": 2384374,
      "optimized": true
    },
    {
      "id": "n6-silabo-practicas-pre-profesionales-i-servicio-comunitario",
      "level": 6,
      "itinerary": "",
      "title": "PRÁCTICAS PRE PROFESIONALES I (SERVICIO COMUNITARIO)",
      "sourceName": "PRÁCTICAS PRE PROFESIONALES I (SERVICIO COMUNITARIO).pdf",
      "path": "assets/syllabi/docs/n6-silabo-practicas-pre-profesionales-i-servicio-comunitario.pdf",
      "pages": 3,
      "originalSize": 2384773,
      "size": 2384043,
      "optimized": true
    },
    {
      "id": "n7-silabo-equipo-industrial",
      "level": 7,
      "itinerary": "",
      "title": "EQUIPO INDUSTRIAL",
      "sourceName": "EQUIPO INDUSTRIAL(1).pdf",
      "path": "assets/syllabi/docs/n7-silabo-equipo-industrial.pdf",
      "pages": 3,
      "originalSize": 2384028,
      "size": 2383302,
      "optimized": true
    },
    {
      "id": "n7-silabo-equipo-industrial-2",
      "level": 7,
      "itinerary": "",
      "title": "EQUIPO INDUSTRIAL",
      "sourceName": "EQUIPO INDUSTRIAL.pdf",
      "path": "assets/syllabi/docs/n7-silabo-equipo-industrial-2.pdf",
      "pages": 4,
      "originalSize": 1871234,
      "size": 1870496,
      "optimized": true
    },
    {
      "id": "n7-silabo-marketing",
      "level": 7,
      "itinerary": "",
      "title": "MARKETING",
      "sourceName": "MARKETING.pdf",
      "path": "assets/syllabi/docs/n7-silabo-marketing.pdf",
      "pages": 3,
      "originalSize": 1842735,
      "size": 1842061,
      "optimized": true
    },
    {
      "id": "n7-silabo-matematica-financiera",
      "level": 7,
      "itinerary": "",
      "title": "MATEMÁTICA FINANCIERA",
      "sourceName": "MATEMÁTICA FINANCIERA.pdf",
      "path": "assets/syllabi/docs/n7-silabo-matematica-financiera.pdf",
      "pages": 2,
      "originalSize": 1814149,
      "size": 1813539,
      "optimized": true
    },
    {
      "id": "n7-silabo-organizacion-de-la-produccion",
      "level": 7,
      "itinerary": "",
      "title": "ORGANIZACIÓN DE LA PRODUCCIÓN",
      "sourceName": "ORGANIZACIÓN DE LA PRODUCCIÓN(1).pdf",
      "path": "assets/syllabi/docs/n7-silabo-organizacion-de-la-produccion.pdf",
      "pages": 3,
      "originalSize": 2385654,
      "size": 2384888,
      "optimized": true
    },
    {
      "id": "n7-silabo-organizacion-de-la-produccion-2",
      "level": 7,
      "itinerary": "",
      "title": "ORGANIZACIÓN DE LA PRODUCCIÓN",
      "sourceName": "ORGANIZACIÓN DE LA PRODUCCIÓN.pdf",
      "path": "assets/syllabi/docs/n7-silabo-organizacion-de-la-produccion-2.pdf",
      "pages": 3,
      "originalSize": 1842713,
      "size": 1842039,
      "optimized": true
    },
    {
      "id": "n7-silabo-practicas-pre-profesionales-ii-laborales-1",
      "level": 7,
      "itinerary": "",
      "title": "PRÁCTICAS PRE PROFESIONALES II (LABORALES 1)",
      "sourceName": "PRÁCTICAS PRE PROFESIONALES II (LABORALES 1).pdf",
      "path": "assets/syllabi/docs/n7-silabo-practicas-pre-profesionales-ii-laborales-1.pdf",
      "pages": 3,
      "originalSize": 2384424,
      "size": 2383694,
      "optimized": true
    },
    {
      "id": "n8-silabo-gestion-ambiental-empresarial",
      "level": 8,
      "itinerary": "",
      "title": "GESTIÓN AMBIENTAL EMPRESARIAL",
      "sourceName": "GESTIÓN AMBIENTAL EMPRESARIAL.pdf",
      "path": "assets/syllabi/docs/n8-silabo-gestion-ambiental-empresarial.pdf",
      "pages": 3,
      "originalSize": 1842943,
      "size": 1842269,
      "optimized": true
    },
    {
      "id": "n8-silabo-gestion-de-calidad",
      "level": 8,
      "itinerary": "",
      "title": "GESTIÓN DE CALIDAD",
      "sourceName": "GESTIÓN DE CALIDAD.pdf",
      "path": "assets/syllabi/docs/n8-silabo-gestion-de-calidad.pdf",
      "pages": 3,
      "originalSize": 1842774,
      "size": 1842100,
      "optimized": true
    },
    {
      "id": "n8-silabo-ingenieria-del-mantenimiento",
      "level": 8,
      "itinerary": "",
      "title": "INGENIERÍA DEL MANTENIMIENTO",
      "sourceName": "INGENIERÍA DEL MANTENIMIENTO.pdf",
      "path": "assets/syllabi/docs/n8-silabo-ingenieria-del-mantenimiento.pdf",
      "pages": 5,
      "originalSize": 1902987,
      "size": 1902185,
      "optimized": true
    },
    {
      "id": "n8-silabo-logistica-y-cadena-de-suministros",
      "level": 8,
      "itinerary": "",
      "title": "LOGÍSTICA Y CADENA DE SUMINISTROS",
      "sourceName": "LOGÍSTICA Y CADENA DE SUMINISTROS.pdf",
      "path": "assets/syllabi/docs/n8-silabo-logistica-y-cadena-de-suministros.pdf",
      "pages": 3,
      "originalSize": 1843232,
      "size": 1842558,
      "optimized": true
    },
    {
      "id": "n8-silabo-practicas-pre-profesionales-iii-laborales-2",
      "level": 8,
      "itinerary": "",
      "title": "PRÁCTICAS PRE PROFESIONALES III (LABORALES 2)",
      "sourceName": "PRÁCTICAS PRE PROFESIONALES III (LABORALES 2).pdf",
      "path": "assets/syllabi/docs/n8-silabo-practicas-pre-profesionales-iii-laborales-2.pdf",
      "pages": 3,
      "originalSize": 2383308,
      "size": 2382578,
      "optimized": true
    },
    {
      "id": "n8-silabo-sistemas-de-control-de-la-produccion",
      "level": 8,
      "itinerary": "",
      "title": "SISTEMAS DE CONTROL DE LA PRODUCCIÓN",
      "sourceName": "SISTEMAS DE CONTROL DE LA PRODUCCIÓN.pdf",
      "path": "assets/syllabi/docs/n8-silabo-sistemas-de-control-de-la-produccion.pdf",
      "pages": 3,
      "originalSize": 1841768,
      "size": 1841094,
      "optimized": true
    },
    {
      "id": "n9-silabo-diseno-experimental",
      "level": 9,
      "itinerary": "",
      "title": "DISEÑO EXPERIMENTAL",
      "sourceName": "DISEÑO EXPERIMENTAL.pdf",
      "path": "assets/syllabi/docs/n9-silabo-diseno-experimental.pdf",
      "pages": 3,
      "originalSize": 1844805,
      "size": 1844131,
      "optimized": true
    },
    {
      "id": "n9-silabo-gestion-financiera",
      "level": 9,
      "itinerary": "",
      "title": "GESTIÓN FINANCIERA",
      "sourceName": "GESTIÓN FINANCIERA.pdf",
      "path": "assets/syllabi/docs/n9-silabo-gestion-financiera.pdf",
      "pages": 3,
      "originalSize": 1847408,
      "size": 1846697,
      "optimized": true
    },
    {
      "id": "n9-silabo-instrumentacion-y-control",
      "level": 9,
      "itinerary": "",
      "title": "INSTRUMENTACIÓN Y CONTROL",
      "sourceName": "INSTRUMENTACIÓN Y CONTROL.pdf",
      "path": "assets/syllabi/docs/n9-silabo-instrumentacion-y-control.pdf",
      "pages": 3,
      "originalSize": 2383556,
      "size": 2382822,
      "optimized": true
    },
    {
      "id": "n9-itinerario-manufacturing-lean-manufacturing-y-6-sigma-i-i1",
      "level": 9,
      "itinerary": "Itinerario Manufacturing",
      "title": "LEAN MANUFACTURING Y 6 SIGMA (I) I1",
      "sourceName": "LEAN MANUFACTURING Y 6 SIGMA (I) I1.pdf",
      "path": "assets/syllabi/docs/n9-itinerario-manufacturing-lean-manufacturing-y-6-sigma-i-i1.pdf",
      "pages": 3,
      "originalSize": 2386331,
      "size": 2385601,
      "optimized": true
    },
    {
      "id": "n9-itinerario-servicios-lean-services-y-sigma-sigma-i-i2",
      "level": 9,
      "itinerary": "Itinerario Servicios",
      "title": "LEAN SERVICES Y SIGMA SIGMA (I) I2",
      "sourceName": "LEAN SERVICES Y SIGMA SIGMA (I) I2.pdf",
      "path": "assets/syllabi/docs/n9-itinerario-servicios-lean-services-y-sigma-sigma-i-i2.pdf",
      "pages": 3,
      "originalSize": 1842536,
      "size": 1841862,
      "optimized": true
    },
    {
      "id": "n9-silabo-practicas-pre-profesionales-iv-laborales-3",
      "level": 9,
      "itinerary": "",
      "title": "PRÁCTICAS PRE PROFESIONALES IV (LABORALES 3)",
      "sourceName": "PRÁCTICAS PRE PROFESIONALES IV (LABORALES 3).pdf",
      "path": "assets/syllabi/docs/n9-silabo-practicas-pre-profesionales-iv-laborales-3.pdf",
      "pages": 3,
      "originalSize": 2384446,
      "size": 2383716,
      "optimized": true
    },
    {
      "id": "n9-silabo-sistemas-de-informacion-estrategica",
      "level": 9,
      "itinerary": "",
      "title": "SISTEMAS DE INFORMACIÓN ESTRATÉGICA",
      "sourceName": "SISTEMAS DE INFORMACIÓN ESTRATÉGICA.pdf",
      "path": "assets/syllabi/docs/n9-silabo-sistemas-de-informacion-estrategica.pdf",
      "pages": 3,
      "originalSize": 1842314,
      "size": 1841640,
      "optimized": true
    },
    {
      "id": "n9-silabo-unidad-de-integracion-curricular-1",
      "level": 9,
      "itinerary": "",
      "title": "UNIDAD DE INTEGRACIÓN CURRICULAR 1",
      "sourceName": "UNIDAD DE INTEGRACIÓN CURRICULAR 1.pdf",
      "path": "assets/syllabi/docs/n9-silabo-unidad-de-integracion-curricular-1.pdf",
      "pages": 3,
      "originalSize": 2384733,
      "size": 2384003,
      "optimized": true
    }
  ]
};
